# Generated by Django 2.1.7 on 2019-06-24 11:50

from django.db import migrations, models
import django.db.models.manager
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('myfield', markdownx.models.MarkdownxField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'Article',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=40, null=True, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='名称')),
                ('is_Delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
